### ISSUE TITLE
 TypeError: reduce_max() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by molyswu** [desire2020/CoT#1]
Hi ,
 Try to python cot.py
  File "F:\study\EBGAN\CoT\Cooperative-Training\generator.py", line 57, in _g_recurrence
    T_t = tf.stop_gradient(tf.reduce_max(-log_prob, axis=-1, keepdims=True))

TypeError: reduce_max() got an unexpected keyword argument 'keepdims'

Thonk you for your help

**Comment by desire2020** [comment]
Please update your tensorflow to at least 1.6.0
